spring:
  datasource:
    url: jdbc:mysql://www.linuxprobe.org:3306/crud_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: temp
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  config: classpath:log4j2-dev.xml
mybatis:
  mapperLocations: classpath*:org/linuxprobe/**/mapping/*.xml